# Generated by Django 4.2.3 on 2023-07-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('verification_status', models.BooleanField()),
                ('checker_rate', models.CharField(choices=[('5', '5 Minutes'), ('15', '15 Minutes'), ('30', 'Thirty Minutes'), ('60', '60 Minutes'), ('24', 'Once a day')], default='24', max_length=15)),
            ],
        ),
    ]
