# Generated by Django 4.2.3 on 2023-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0004_alter_websites_checker_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('html_response', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
