# Generated by Django 4.2.3 on 2023-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0006_alter_logs_options_alter_websites_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='website_speed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
