# Generated by Django 4.2.4 on 2023-08-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0008_alter_logs_website_alter_websites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='verification_record',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
