# Generated by Django 4.2.4 on 2023-08-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0009_websites_verification_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='html_response',
            new_name='response_headers',
        ),
    ]
