# Generated by Django 4.2.4 on 2023-08-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0010_rename_html_response_logs_response_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='website_speed',
            field=models.CharField(max_length=100),
        ),
    ]
