# Generated by Django 4.2.4 on 2023-08-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0011_alter_logs_website_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
